# Generated by Django 5.0.2 on 2024-03-01 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('topic', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pinner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image_in_pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.image')),
                ('pin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.pin')),
            ],
        ),
        migrations.CreateModel(
            name='Pin_in_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.board')),
                ('pin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.pin')),
            ],
        ),
        migrations.AddField(
            model_name='pin',
            name='pinner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.pinner'),
        ),
        migrations.AddField(
            model_name='board',
            name='pinner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.pinner'),
        ),
    ]
