# Generated by Django 5.0.2 on 2024-03-01 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pinner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.pinner'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pinner',
            name='mail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
