# Generated by Django 5.0.2 on 2024-03-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_alter_board_pinner_id_alter_pin_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
