# Generated by Django 5.0.2 on 2024-03-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_alter_pin_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_in_pin',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='image_in_pin',
            name='pin_id',
        ),
        migrations.AddField(
            model_name='pin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Image_in_pin',
        ),
    ]
