# Generated by Django 5.0.2 on 2024-03-04 13:00

import pins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0004_remove_image_in_pin_image_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pins.models.user_directory_path),
        ),
    ]
